name = "coffee-excuse-generator"
main = "src/worker.js"
compatibility_date = "2023-06-26"

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# KV Namespace for rate limiting and logging
[[kv_namespaces]]
binding = "COFFEE_KV"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-namespace-id"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Analytics (optional)
[analytics_engine_datasets]
binding = "ANALYTICS"
name = "coffee-excuse-analytics"

# Rate limiting at the edge (optional additional layer)
[rate_limiting]
enabled = true